<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Partido;
use App\Models\Candidato;

class CandidatosDirectorioNacionalSeeder extends Seeder
{
    public function run(): void
    {
        $movimientos = [
            '1' => Partido::where('numero_lista', '1')->first(),
            '3' => Partido::where('numero_lista', '3')->first(),
            '9' => Partido::where('numero_lista', '9')->first(),
            '13' => Partido::where('numero_lista', '13')->first(),
            '21' => Partido::where('numero_lista', '21')->first(),
            '25' => Partido::where('numero_lista', '25')->first(),
            '100' => Partido::where('numero_lista', '100')->first(),
        ];

        $cargo = 'directorio nacional';

        $candidatos = [
            // Coherencia Liberal - Lista 1
            ['lista' => '1', 'nombre' => 'Olga Paredes', 'orden' => 1],
            ['lista' => '1', 'nombre' => 'Fabián Marti', 'orden' => 2],
            ['lista' => '1', 'nombre' => 'Celsa Amada Acosta Lugo', 'orden' => 3],
            ['lista' => '1', 'nombre' => 'Diego López', 'orden' => 4],
            ['lista' => '1', 'nombre' => 'Alma Segovia', 'orden' => 5],
            ['lista' => '1', 'nombre' => 'Dr. Gustavo Guggiari', 'orden' => 6],
            ['lista' => '1', 'nombre' => 'Dra. Jessica Vergara', 'orden' => 7],
            ['lista' => '1', 'nombre' => 'Taguide Picanerai Etacore', 'orden' => 8],
            ['lista' => '1', 'nombre' => 'Carina Cañete Torres', 'orden' => 9],
            ['lista' => '1', 'nombre' => 'Alba Ozuna', 'orden' => 10],
            ['lista' => '1', 'nombre' => 'Armando Sosa Traverzzi', 'orden' => 11],
            ['lista' => '1', 'nombre' => 'Carmen Mendoza', 'orden' => 12],
            ['lista' => '1', 'nombre' => 'Nery Peña', 'orden' => 13],
            ['lista' => '1', 'nombre' => 'Abog. Mirta Rios Chiuzano', 'orden' => 14],
            ['lista' => '1', 'nombre' => 'Martin Gonzalez Osorio', 'orden' => 15],
            ['lista' => '1', 'nombre' => 'Johana Cuenca', 'orden' => 16],
            ['lista' => '1', 'nombre' => 'Diego Bazán', 'orden' => 17],
            ['lista' => '1', 'nombre' => 'Lic. Alicia Benitez', 'orden' => 18],
            ['lista' => '1', 'nombre' => 'Sin Candidato', 'orden' => 19],
            ['lista' => '1', 'nombre' => 'Jessica López', 'orden' => 20],
            ['lista' => '1', 'nombre' => 'Dr. Guido Cuevas Almando', 'orden' => 21],
            ['lista' => '1', 'nombre' => 'Natalia Belén Aguilar', 'orden' => 22],
            ['lista' => '1', 'nombre' => 'Mgtr. Víctor Sosa Traverzzi', 'orden' => 23],
            ['lista' => '1', 'nombre' => 'Lic. Angélica Escurra', 'orden' => 24],
            ['lista' => '1', 'nombre' => 'Prof. Danny Cabrera', 'orden' => 25],
            ['lista' => '1', 'nombre' => 'Eloisa Ibarra Oviedo', 'orden' => 26],
            ['lista' => '1', 'nombre' => 'Jesús María Cardozo Baudry', 'orden' => 27],
            ['lista' => '1', 'nombre' => 'Gladys Mabel Acosta Franco', 'orden' => 28],
            ['lista' => '1', 'nombre' => 'Abog. Juan Chamorro', 'orden' => 29],
            ['lista' => '1', 'nombre' => 'Jorge Ariel Riveros Garcia', 'orden' => 30],
            // Nuevo Liberalismo - Lista 3
            ['lista' => '3', 'nombre' => 'Javier Pereira', 'orden' => 1],
            ['lista' => '3', 'nombre' => 'Agustín Saguier', 'orden' => 2],
            ['lista' => '3', 'nombre' => 'Sonia Fleitas', 'orden' => 3],
            ['lista' => '3', 'nombre' => 'Papu Ríos', 'orden' => 4],
            ['lista' => '3', 'nombre' => 'Horacio Carísimo', 'orden' => 5],
            ['lista' => '3', 'nombre' => 'Dalia Estigarribia', 'orden' => 6],
            ['lista' => '3', 'nombre' => 'Ariel Villagra', 'orden' => 7],
            ['lista' => '3', 'nombre' => 'Diego Riveros', 'orden' => 8],
            ['lista' => '3', 'nombre' => 'Horacio Ortiz', 'orden' => 9],
            ['lista' => '3', 'nombre' => 'Rodrigo Blanco Amarilla', 'orden' => 10],
            ['lista' => '3', 'nombre' => 'Oscar González Drakeford', 'orden' => 11],
            ['lista' => '3', 'nombre' => 'Gustavo Cano', 'orden' => 12],
            ['lista' => '3', 'nombre' => 'Pedro González Ramírez', 'orden' => 13],
            ['lista' => '3', 'nombre' => 'Fabiola Galeano Chamorro', 'orden' => 14],
            ['lista' => '3', 'nombre' => 'Osvaldo Gómez Ojeda', 'orden' => 15],
            ['lista' => '3', 'nombre' => 'Holder Kennedy', 'orden' => 16],
            ['lista' => '3', 'nombre' => 'Waldino Monte da Oca', 'orden' => 17],
            ['lista' => '3', 'nombre' => 'Juliana Boccia Amarilla', 'orden' => 18],
            ['lista' => '3', 'nombre' => 'Regina Ríos', 'orden' => 19],
            ['lista' => '3', 'nombre' => 'Silvio Peña', 'orden' => 20],
            ['lista' => '3', 'nombre' => 'Sonia Medina', 'orden' => 21],
            ['lista' => '3', 'nombre' => 'Miguel Martínez Núñez', 'orden' => 22],
            ['lista' => '3', 'nombre' => 'Daniel Rojas López', 'orden' => 23],
            ['lista' => '3', 'nombre' => 'Daniel Pereira', 'orden' => 24],
            ['lista' => '3', 'nombre' => 'Oscar Rotela', 'orden' => 25],
            ['lista' => '3', 'nombre' => 'David Llano', 'orden' => 26],
            ['lista' => '3', 'nombre' => 'Dra. Nilsa Sánchez V.', 'orden' => 27],
            ['lista' => '3', 'nombre' => 'Fabio Almada Duarte', 'orden' => 28],
            ['lista' => '3', 'nombre' => 'Pedro Ricardo Arias', 'orden' => 29],
            ['lista' => '3', 'nombre' => 'David González', 'orden' => 30],
            // Frente Radical - Lista 9
            ['lista' => '9', 'nombre' => 'Líder Amarilla', 'orden' => 1],
            ['lista' => '9', 'nombre' => 'Vidala Franco', 'orden' => 2],
            ['lista' => '9', 'nombre' => 'Diosnel Aguilera', 'orden' => 3],
            ['lista' => '9', 'nombre' => 'Alba Talavera', 'orden' => 4],
            ['lista' => '9', 'nombre' => 'Celso Maldonado Duarte', 'orden' => 5],
            ['lista' => '9', 'nombre' => 'María Lorena Segovia Azucas', 'orden' => 6],
            ['lista' => '9', 'nombre' => 'Lilian Zayas', 'orden' => 7],
            ['lista' => '9', 'nombre' => 'Luis A. Wagner', 'orden' => 8],
            ['lista' => '9', 'nombre' => 'Mirna Estela Ríos Ojeda', 'orden' => 9],
            ['lista' => '9', 'nombre' => 'Neri Olmedo Rolón', 'orden' => 10],
            ['lista' => '9', 'nombre' => 'Sergio Ortega', 'orden' => 11],
            ['lista' => '9', 'nombre' => 'Juan Ramón Cohene Acuña', 'orden' => 12],
            ['lista' => '9', 'nombre' => 'Yanina Duarte', 'orden' => 13],
            ['lista' => '9', 'nombre' => 'Ancho Ramírez', 'orden' => 14],
            ['lista' => '9', 'nombre' => 'Rossana Rojas', 'orden' => 15],
            ['lista' => '9', 'nombre' => 'Regina Barrios', 'orden' => 16],
            ['lista' => '9', 'nombre' => 'Ailsa Yambay', 'orden' => 17],
            ['lista' => '9', 'nombre' => 'Gustavo Arturo Ojeda', 'orden' => 18],
            ['lista' => '9', 'nombre' => 'Víctor José Risso Medina', 'orden' => 19],
            ['lista' => '9', 'nombre' => 'Carlos Núñez', 'orden' => 20],
            ['lista' => '9', 'nombre' => 'Líder Fabián Almada', 'orden' => 21],
            ['lista' => '9', 'nombre' => 'Rosa Daniela Acosta Denis', 'orden' => 22],
            ['lista' => '9', 'nombre' => 'Félix Arrua', 'orden' => 23],
            ['lista' => '9', 'nombre' => 'Carlos Alberto Cantero Aquino', 'orden' => 24],
            ['lista' => '9', 'nombre' => 'Jazmín Girala', 'orden' => 25],
            ['lista' => '9', 'nombre' => 'Benita Jara Cañiza', 'orden' => 26],
            ['lista' => '9', 'nombre' => 'Juanma Benítez', 'orden' => 27],
            ['lista' => '9', 'nombre' => 'Alba Invernizzi', 'orden' => 28],
            ['lista' => '9', 'nombre' => 'Robert Bento', 'orden' => 29],
            ['lista' => '9', 'nombre' => 'Maricel Ortega', 'orden' => 30],
            // Cambio para el Cambio - Lista 13
            ['lista' => '13', 'nombre' => 'Pedro Regalado Riveros', 'orden' => 1],
            ['lista' => '13', 'nombre' => 'Oscar Guanes', 'orden' => 2],
            ['lista' => '13', 'nombre' => 'Algredo Sebastián Jaeggli Valdés', 'orden' => 3],
            ['lista' => '13', 'nombre' => 'César Rubén Cristaldo Avalos', 'orden' => 4],
            ['lista' => '13', 'nombre' => 'Adahia Saray Echagüe Zaracho', 'orden' => 5],
            ['lista' => '13', 'nombre' => 'Naoki Shirozawa Shirosawa', 'orden' => 6],
            ['lista' => '13', 'nombre' => 'Miguel Ángel Guillen Gómez', 'orden' => 7],
            ['lista' => '13', 'nombre' => 'Rubén Nicolás Rojas Adorno', 'orden' => 8],
            ['lista' => '13', 'nombre' => 'Rodrigo Arza de Sousa', 'orden' => 9],
            ['lista' => '13', 'nombre' => 'Teresa Marina Aranda de Hidalgo', 'orden' => 10],
            ['lista' => '13', 'nombre' => 'Blas Roberto Cabañas', 'orden' => 11],
            ['lista' => '13', 'nombre' => 'Jorge Daniel Ferreira', 'orden' => 12],
            ['lista' => '13', 'nombre' => 'Walter Ibán Echagüe Figueredo', 'orden' => 13],
            ['lista' => '13', 'nombre' => 'Valentín Galeano Osorio', 'orden' => 14],
            ['lista' => '13', 'nombre' => 'Licula Vázquez Miranda', 'orden' => 15],
            ['lista' => '13', 'nombre' => 'David Emilio Hidalgo Aranda', 'orden' => 16],
            ['lista' => '13', 'nombre' => 'Gerardo Darío Causarano Cáceres', 'orden' => 17],
            ['lista' => '13', 'nombre' => 'Algredo Manuel Rojas dos Santos', 'orden' => 18],
            ['lista' => '13', 'nombre' => 'Juan Antonio Ramírez Dittrich', 'orden' => 19],
            ['lista' => '13', 'nombre' => 'Mercedes González Zelaya', 'orden' => 20],
            ['lista' => '13', 'nombre' => 'Jorge Ibán Arias Fretes', 'orden' => 21],
            ['lista' => '13', 'nombre' => 'NO TIENE CANDIDATO', 'orden' => 22],
            ['lista' => '13', 'nombre' => 'Celso Gustavo Gamarra Pacua', 'orden' => 23],
            ['lista' => '13', 'nombre' => 'Celso Ibán Garicox Vera', 'orden' => 24],
            ['lista' => '13', 'nombre' => 'Maracenta Iglesias Arza', 'orden' => 25],
            ['lista' => '13', 'nombre' => 'Félix Méndez Vergara', 'orden' => 26],
            ['lista' => '13', 'nombre' => 'Osmar David Ocampos Peralta', 'orden' => 27],
            ['lista' => '13', 'nombre' => 'Isabelino Cañete Viñales', 'orden' => 28],
            ['lista' => '13', 'nombre' => 'José David Vázquez', 'orden' => 29],
            ['lista' => '13', 'nombre' => 'Patricia Giselli Vera de González', 'orden' => 30],
            // Siglo 21 - Lista 21
            ['lista' => '21', 'nombre' => 'Eugenio Dure Giménez', 'orden' => 1],
            ['lista' => '21', 'nombre' => 'Derlis Antonio Valdez Ponillux', 'orden' => 2],
            ['lista' => '21', 'nombre' => 'Miguel Sabino Fernández', 'orden' => 3],
            ['lista' => '21', 'nombre' => 'Dario Ovando González', 'orden' => 4],
            ['lista' => '21', 'nombre' => 'Ramón Manuel Guerrero Caballero', 'orden' => 5],
            ['lista' => '21', 'nombre' => 'Wilma Carlita Becvort de Núñez', 'orden' => 6],
            ['lista' => '21', 'nombre' => 'Hugo Narciso Ruiz Díaz Rivas', 'orden' => 7],
            ['lista' => '21', 'nombre' => 'Freddy Ferreira', 'orden' => 8],
            ['lista' => '21', 'nombre' => 'Alfredo Domingo Domínguez Dávalos', 'orden' => 9],
            ['lista' => '21', 'nombre' => 'Antonia del Pilar Rodríguez Vera', 'orden' => 10],
            ['lista' => '21', 'nombre' => 'Amancio Ruiz Díaz Rivas', 'orden' => 11],
            ['lista' => '21', 'nombre' => 'Hipólito Felipe Rodríguez Paniagua', 'orden' => 12],
            ['lista' => '21', 'nombre' => 'Juan José Flores Esquivel', 'orden' => 13],
            ['lista' => '21', 'nombre' => 'Oscar Ramón Martínez', 'orden' => 14],
            ['lista' => '21', 'nombre' => 'Dora Anicia Ovelar Velázquez', 'orden' => 15],
            ['lista' => '21', 'nombre' => 'Francisco Castro Ocampo', 'orden' => 16],
            ['lista' => '21', 'nombre' => 'José Adrián Martínez Delgado', 'orden' => 17],
            ['lista' => '21', 'nombre' => 'Benjamín Manuel Benítez Ruiz Díaz', 'orden' => 18],
            ['lista' => '21', 'nombre' => 'Albino Ocampos Andino', 'orden' => 19],
            ['lista' => '21', 'nombre' => 'Rosa Estela Escobar Ocampos', 'orden' => 20],
            ['lista' => '21', 'nombre' => 'Juan Domingciano Cardozo', 'orden' => 21],
            ['lista' => '21', 'nombre' => 'David Fernando Ruiz Díaz Silva', 'orden' => 22],
            ['lista' => '21', 'nombre' => 'Cayo Cantero Ortiz', 'orden' => 23],
            ['lista' => '21', 'nombre' => 'Juan Bautista Miranda', 'orden' => 24],
            ['lista' => '21', 'nombre' => 'Karina Gissel López Escobar', 'orden' => 25],
            ['lista' => '21', 'nombre' => 'César Ojeda Cañete', 'orden' => 26],
            ['lista' => '21', 'nombre' => 'Delio Ramón Ruiz Díaz', 'orden' => 27],
            ['lista' => '21', 'nombre' => 'Marcos Emilio Molinas', 'orden' => 28],
            ['lista' => '21', 'nombre' => 'Dionicio Sanabria Esteche', 'orden' => 29],
            ['lista' => '21', 'nombre' => 'Francisca Ruiz Díaz Barrios', 'orden' => 30],
            // Oñondivepa - Lista 25
            ['lista' => '25', 'nombre' => 'Ariel Perfecto Fonseca Legal', 'orden' => 1],
            ['lista' => '25', 'nombre' => 'Luis Alberto Rivarola Paredes', 'orden' => 2],
            ['lista' => '25', 'nombre' => 'Mario Cristaldo Amaro', 'orden' => 3],
            ['lista' => '25', 'nombre' => 'Rose Margaret Brandt Duarte', 'orden' => 4],
            ['lista' => '25', 'nombre' => 'Gustavo Flecha', 'orden' => 5],
            ['lista' => '25', 'nombre' => 'Marco Aguilera Figueroa', 'orden' => 6],
            ['lista' => '25', 'nombre' => 'Johanna Osmilda Cubas Paniagua', 'orden' => 7],
            ['lista' => '25', 'nombre' => 'Carlos Antonio Zárate', 'orden' => 8],
            ['lista' => '25', 'nombre' => 'Ilda Fonseca Legal', 'orden' => 9],
            ['lista' => '25', 'nombre' => 'Ruth Alcira Sosa Burgos', 'orden' => 10],
            ['lista' => '25', 'nombre' => 'Rubén Darío Medina Candia', 'orden' => 11],
            ['lista' => '25', 'nombre' => 'Crshtian Villalba Arce', 'orden' => 12],
            ['lista' => '25', 'nombre' => 'Francisco Antonio Silvero Venialvos', 'orden' => 13],
            ['lista' => '25', 'nombre' => 'Rubén Darío Rojas Garay', 'orden' => 14],
            ['lista' => '25', 'nombre' => 'Basilio Chamorro Garcete', 'orden' => 15],
            ['lista' => '25', 'nombre' => 'César Silvio Núñez Farías', 'orden' => 16],
            ['lista' => '25', 'nombre' => 'Liz Rocío Estigarribia Denis', 'orden' => 17],
            ['lista' => '25', 'nombre' => 'Esteban Aguilar Aguilera', 'orden' => 18],
            ['lista' => '25', 'nombre' => 'César Ojeda Cañete', 'orden' => 19],
            ['lista' => '25', 'nombre' => 'Viviana Concepción Espinoza Quintana', 'orden' => 20],
            ['lista' => '25', 'nombre' => 'Gloria Leonida Martínez Silva', 'orden' => 21],
            ['lista' => '25', 'nombre' => 'Mirtha Soledad Alemán González', 'orden' => 22],
            ['lista' => '25', 'nombre' => 'César Mendoza Acosta', 'orden' => 23],
            ['lista' => '25', 'nombre' => 'Roque Acosta Machuca', 'orden' => 24],
            ['lista' => '25', 'nombre' => 'Lidia Beatriz Godoy Quintana', 'orden' => 25],
            ['lista' => '25', 'nombre' => 'Ever Quintana Lezcano', 'orden' => 26],
            ['lista' => '25', 'nombre' => 'Yicela Romina Ovelar Noe', 'orden' => 27],
            ['lista' => '25', 'nombre' => 'Fidel Antonio Salinas Mereles', 'orden' => 28],
            ['lista' => '25', 'nombre' => 'María Guadalupe Ramírez Peralta', 'orden' => 29],
            ['lista' => '25', 'nombre' => 'Luana Mabel Torres Quintana', 'orden' => 30],
            // Diálogo Azul - Lista 100
            ['lista' => '100', 'nombre' => 'Dra. Nuria Isnardi', 'orden' => 1],
            ['lista' => '100', 'nombre' => 'Héctor Céspedes Flores', 'orden' => 2],
            ['lista' => '100', 'nombre' => 'Blanca Lila Mignarro', 'orden' => 3],
            ['lista' => '100', 'nombre' => 'Roque Godoy', 'orden' => 4],
            ['lista' => '100', 'nombre' => 'Andrés Rojas', 'orden' => 5],
            ['lista' => '100', 'nombre' => 'Octavio Shatp', 'orden' => 6],
            ['lista' => '100', 'nombre' => 'Basilisa Vázquez', 'orden' => 7],
            ['lista' => '100', 'nombre' => 'César Ferreira', 'orden' => 8],
            ['lista' => '100', 'nombre' => 'Julio Villalba', 'orden' => 9],
            ['lista' => '100', 'nombre' => 'Darío Cabral', 'orden' => 10],
            ['lista' => '100', 'nombre' => 'Eutilio Riveros', 'orden' => 11],
            ['lista' => '100', 'nombre' => 'Edu Giménez', 'orden' => 12],
            ['lista' => '100', 'nombre' => 'Eva de Witte', 'orden' => 13],
            ['lista' => '100', 'nombre' => 'Daniel Villordo', 'orden' => 14],
            ['lista' => '100', 'nombre' => 'Pedro A. Chih Lin', 'orden' => 15],
            ['lista' => '100', 'nombre' => 'Stella Rolón', 'orden' => 16],
            ['lista' => '100', 'nombre' => 'Sannie Ibarrola', 'orden' => 17],
            ['lista' => '100', 'nombre' => 'Keke Julio', 'orden' => 18],
            ['lista' => '100', 'nombre' => 'Delio Saldivar', 'orden' => 19],
            ['lista' => '100', 'nombre' => 'Fidel León', 'orden' => 20],
            ['lista' => '100', 'nombre' => 'Naty Fretes', 'orden' => 21],
            ['lista' => '100', 'nombre' => 'Sanfo Benítez', 'orden' => 22],
            ['lista' => '100', 'nombre' => 'Dani Báez', 'orden' => 23],
            ['lista' => '100', 'nombre' => 'Adejaime Pavei', 'orden' => 24],
            ['lista' => '100', 'nombre' => 'Vicente Denis', 'orden' => 25],
            ['lista' => '100', 'nombre' => 'Laly Parra', 'orden' => 26],
            ['lista' => '100', 'nombre' => 'Tapi Enciso', 'orden' => 27],
            ['lista' => '100', 'nombre' => 'Wilma Bareiro', 'orden' => 28],
            ['lista' => '100', 'nombre' => 'Mirna Ortiz de Goldner', 'orden' => 29],
            ['lista' => '100', 'nombre' => 'Félix Ibañez', 'orden' => 30],
        ];

        foreach ($candidatos as $c) {
            $partido = $movimientos[$c['lista']] ?? null;
            if ($partido) {
                Candidato::updateOrCreate(
                    [
                        'partido_id' => $partido->id,
                        'nombre_completo' => $c['nombre'],
                        'cargo' => $cargo,
                    ],
                    [
                        'numero_orden' => $c['orden'],
                        'activo' => true,
                    ]
                );
            }
        }

        $this->command->info('Candidatos a directorio nacional cargados correctamente. Total: ' . count($candidatos));
    }
}
